This is a Teamcenter 8.1 version of USER_ask_new_seqno (see user_part_no.c)
which has been modified to allow sequencing by increments of 1 instead of 10.

Similar methods should work in other TC versions.

/*=============================================================================
extern int USER_ask_new_seqno (tag_t parent_bom_rev, tag_t item, char **seqno)
{
    int ifail;
    int decision  = NO_CUSTOMIZATION;

    BMF_EXECUTE_USER_EXIT_EXTENSIONS(("PSOccurrence",
                                      "seq_no",
                                      PSO_ask_new_sequence_no_msg,
                                      parent_bom_rev,
                                      item,
                                      seqno));

    ifail = CUSTOM_execute_callbacks ( &decision,
                                       "USER_ask_new_seqno",
                                       parent_bom_rev,
                                       item,
                                       seqno
                                     );

    if ( ifail != ITK_ok || decision != NO_CUSTOMIZATION )
    {
        return ifail;
    }

    // <SYN> 19-June-2006 sequence number generation task is now moved to PSBOMViewRevision Class.
    // which includes checking sequnec number generation mode and generating
    // new sequence number based on that.
    if (parent_bom_rev == null_tag)
    {
       TC_preference_search_scope_t old_scope;
       char  *seqnoModePref = 0;
       char *my_string = (char *)MEM_alloc ( strlen ( DEFAULT_SEQUENCE_NO ) + 1 );

       PREF_ask_search_scope(&old_scope);
       PREF_set_search_scope(TC_preference_site);
       PREF_ask_char_value("PS_new_seqno_mode", 0, &seqnoModePref);
       PREF_set_search_scope(old_scope);

       if ( (seqnoModePref) && (strcmp(seqnoModePref, "none")==0) )
       {
           strcpy ( my_string, "" );
       }
       else
       {
           strcpy ( my_string, DEFAULT_SEQUENCE_NO );
       }
       *seqno = my_string;
    }
    else
    {
        char *sequence_no = 0;

    /*  BEGIN Add for sequencing by 1 instead of 10 */
        char *my_string = NULL;
        char *occurrence_seq = NULL;
        char match[5] = "False";
        int n_occurrences = 0;
        int i = 0;
        tag_t *t_occurrences;
    /*  END Add for sequencing by 1 instead of 10 */


        int ifail = PS_bvr_ask_default_next_seq_no(parent_bom_rev,item,&sequence_no);
        if( ifail != ITK_ok )
        {
           if (ifail != PS_no_seq_no)
           {
               // could return DEFAULT_SEQUENCE_NO, but since other
               // occurrences have no sequence number I doubt this
               // I doubt this should.
                return ITK_ok;
           }
           else if( ifail != ITK_ok )
           {
               EMH_clear_last_error(PS_no_seq_no); // NKM 21/8/98 - should clear valid error
           }
        }

    /*  BEGIN Add for sequencing by 1 instead of 10 */

/*  Addition so sequence numbers are generated by one and not ten.  Changed
    the DEFAULT_SEQUENCE_NO to "1".  Getting the list of occurrences in
    the BVR and looping through them to check for a match.  If match is
    found keep existing find number.  if match is not found subtract 9
    from the sequence number.

    was:
    *seqno = sequence_no;
*/

        PS_list_occurrences_of_bvr(parent_bom_rev, &n_occurrences, &t_occurrences);

        for( i = 0; i < n_occurrences; i ++ ) //looping through occurrences
        {
            PS_ask_seq_no(parent_bom_rev, t_occurrences[i], &occurrence_seq);

            if ( tc_strcasecmp(occurrence_seq, sequence_no) == 0)
            {
                TC_write_syslog("Found Seq Match\n");
                strcpy(match, "True");
                *seqno = sequence_no;
                break;
            }
            else
            {
                TC_write_syslog("No Seq Match\n");
                strcpy(match, "False");
            }
        }

        if ( tc_strcasecmp(match, "False") == 0)
        {
            my_string = (char *)MEM_alloc ( strlen ( sequence_no ) + 1);
            sprintf(my_string, "%d", atoi(sequence_no) - 9);
            *seqno = my_string;
        }
    /*  END Add for sequencing by 1 instead of 10 */

    }
    return ITK_ok;
}
